export const catalog = [
    {
      id: 'section__water',
      title: "Вода",
      cards: [
        {
          name: "Zer0P Вода негазированная 1",
          imgSrc1x: "/img/middle__water.png",
          imgSrc2x: "/img/2x/middle__water__2x.png",
          webpSrc1x: "/img/webp/middle__water.webp",
          webpSrc2x: "/img/webp/middle__water__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          sale: 20,
          quantity: 3,
          id: "1sw1p"
        },
        {
          name: "Zer0P Вода негазированная 2",
          imgSrc1x: "/img/middle__water.png",
          imgSrc2x: "/img/2x/middle__water__2x.png",
          webpSrc1x: "/img/webp/middle__water.webp",
          webpSrc2x: "/img/webp/middle__water__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "1sw2p"
        },
        {
          name: "Zer0P Вода негазированная 3",
          imgSrc1x: "/img/middle__water.png",
          imgSrc2x: "/img/2x/middle__water__2x.png",
          webpSrc1x: "/img/webp/middle__water.webp",
          webpSrc2x: "/img/webp/middle__water__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "1sw3p"
        },
        {
          name: "Foco Кокосовая вода",
          imgSrc1x: "/img/foco__coconut__water.png",
          imgSrc2x: "/img/2x/foco__coconut__water__2x.png",
          webpSrc1x: "/img/webp/foco__coconut__water.webp",
          webpSrc2x: "/img/webp/foco__coconut__water__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "1sw4p"
        },
      ],
    },
    {
      id: 'section__juice',
      title: "Соки",
      cards: [
        {
          name: "CОК АПЕЛЬСИНОВЫЙ СВЕЖЕВЫЖАТЫЙ",
          imgSrc1x: "/img/2sj1i.png",
          imgSrc2x: "/img/2x/2sj1i__2x.png",
          webpSrc1x: "/img/webp/2sj1i.webp",
          webpSrc2x: "/img/webp/2sj1i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "2sj1p"
        },
        {
          name: "СОК ВИШНЕВЫЙ СВЕЖЕВЫЖАТЫЙ",
          imgSrc1x: "/img/2sj2i.png",
          imgSrc2x: "/img/2x/2sj2i__2x.png",
          webpSrc1x: "/img/webp/2sj2i.webp",
          webpSrc2x: "/img/webp/2sj2i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "2sj2p"
        },
        {
          name: "ITO NOEN СОК ЮДЗУ 100%я",
          imgSrc1x: "/img/2sj3i.png",
          imgSrc2x: "/img/2x/2sj3i__2x.png",
          webpSrc1x: "/img/webp/2sj3i.webp",
          webpSrc2x: "/img/webp/2sj3i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "2sj3p"
        },
        {
          name: "СОК ХОЛОДНОГО ОТЖИМА CITRUS 3",
          imgSrc1x: "/img/2sj4i.png",
          imgSrc2x: "/img/2x/2sj4i__2x.png",
          webpSrc1x: "/img/webp/2sj4i.webp",
          webpSrc2x: "/img/webp/2sj4i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "грейпфрут свежий, мята свежая",
          quantity: 3,
          id: "2sj4p",
          productDescription: "Citrus – соки богаты витамином С, стимулируют обмен веществ и мобилизуют силы.",
          ratingValue:"4.8"
        },
      ],
    },
    {
      id: 'section__fruit__drink',
      title: "Морсы",
      cards: [
        {
          name: "МОРС ИЗ ЧЕРНОЙ СМОРОДИНЫ",
          imgSrc1x: "/img/3sf-d1j.png",
          imgSrc2x: "/img/2x/3sf-d1j__2x.png",
          webpSrc1x: "/img/webp/3sf-d1j.webp",
          webpSrc2x: "/img/webp/3sf-d1j__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "3sf-d1p"
        },
        {
          name: "МОРС ИЗ ОБЛЕПИХИ",
          imgSrc1x: "/img/3sf-d2j.png",
          imgSrc2x: "/img/2x/3sf-d2j__2x.png",
          webpSrc1x: "/img/webp/3sf-d2j.webp",
          webpSrc2x: "/img/webp/3sf-d2j__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "3sf-d2p"
        },
        {
          name: "МОРС ИЗ БРУСНИКИ",
          imgSrc1x: "/img/3sf-d3j.png",
          imgSrc2x: "/img/2x/3sf-d3j__2x.png",
          webpSrc1x: "/img/webp/3sf-d3j.webp",
          webpSrc2x: "/img/webp/3sf-d3j__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "3sf-d3p"
        },
        {
          name: "МОРС ИЗ КЛЮКВЫ",
          imgSrc1x: "/img/3sf-d4j.png",
          imgSrc2x: "/img/2x/3sf-d4j__2x.png",
          webpSrc1x: "/img/webp/3sf-d4j.webp",
          webpSrc2x: "/img/webp/3sf-d4j__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "3sf-d4p"
        },
      ],
    },
    {
      id: 'section__smoothie',
      title: "Смузи",
      cards: [
        {
          name: "CLEAR BARN СМУЗИ HEY, МИНЬОН!",
          imgSrc1x: "/img/4ss1i.png",
          imgSrc2x: "/img/2x/4ss1i__2x.png",
          webpSrc1x: "/img/webp/4ss1i.webp",
          webpSrc2x: "/img/webp/4ss1i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "4ss1p"
        },
        {
          name: "CLEAR BARN СМУЗИ COSMOS",
          imgSrc1x: "/img/4ss2i.png",
          imgSrc2x: "/img/2x/4ss2i__2x.png",
          webpSrc1x: "/img/webp/4ss2i.webp",
          webpSrc2x: "/img/webp/4ss2i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "4ss2p"
        },
        {
          name: "CLEAR BARN СМУЗИ MR. FLANINGO ",
          imgSrc1x: "/img/4ss3i.png",
          imgSrc2x: "/img/2x/4ss3i__2x.png",
          webpSrc1x: "/img/webp/4ss3i.webp",
          webpSrc2x: "/img/webp/4ss3i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "4ss3p"
        },
        {
          name: "CLEAR BARN СМУЗИ SUPER GIRL",
          imgSrc1x: "/img/4ss4i.png",
          imgSrc2x: "/img/2x/4ss4i__2x.png",
          webpSrc1x: "/img/webp/4ss4i.webp",
          webpSrc2x: "/img/webp/4ss4i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "4ss4p"
        },
      ],
    },
    {
      id: 'section__sport__drink',
      title: "Спортивные напикти",
      cards: [
        {
          name: "ИЗОТОНИК POWERADE",
          imgSrc1x: "/img/5ss-d1i.png",
          imgSrc2x: "/img/2x/5ss-d1i__2x.png",
          webpSrc1x: "/img/webp/5ss-d1i.webp",
          webpSrc2x: "/img/webp/5ss-d1i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "5ss-d1p"
        },
        {
          name: "ГИПОТоНИЧЕСКИЙ НАПИТОК",
          imgSrc1x: "/img/5ss-d2i.png",
          imgSrc2x: "/img/2x/5ss-d2i__2x.png",
          webpSrc1x: "/img/webp/5ss-d2i.webp",
          webpSrc2x: "/img/webp/5ss-d2i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "5ss-d2p"
        },
      ],
    },
  ];