export const catalog = [
    {
      id: 'section__water',
      title: "Вода",
      cards: [
        {
          name: "Zer0P Вода негазированная 1",
          imgSrc1x: "/img/middle__water.png",
          imgSrc2x: "/img/2x/middle__water__2x.png",
          webpSrc1x: "/img/webp/middle__water.webp",
          webpSrc2x: "/img/webp/middle__water__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "",
          sale: 50,
          quantity: 3,
          id: "1sw1p"
        },
        {
          name: "Zer0P Вода",
          imgSrc1x: "/img/middle__water.png",
          imgSrc2x: "/img/2x/middle__water__2x.png",
          webpSrc1x: "/img/webp/middle__water.webp",
          webpSrc2x: "/img/webp/middle__water__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "",
          quantity: 3,
          id: "1sw2p"
        },
        {
          name: "Напиток LEGEND OF BAIKAL Лайм негазированный",
          imgSrc1x: "/img/1sw3p.png",
          imgSrc2x: "/img/2x/1sw3p__2x.png",
          webpSrc1x: "/img/1sw3p.png",
          webpSrc2x: "/img/2x/1sw3p__2x.png",
          volumes: [330],
          prices: [129],
          ingredients: "Вода подготовленная, регулятор кислотности кислота лимонная, ароматизатор натуральный «Лайм», подсластитель сукралоза, премикс витаминный (ниацин, пантотеновая кислота, Витамин В6, витамин В1, биотин).",
          quantity: 3,
          id: "1sw3p"
        },
        {
          name: "Foco Кокосовая вода",
          imgSrc1x: "/img/foco__coconut__water.png",
          imgSrc2x: "/img/2x/foco__coconut__water__2x.png",
          webpSrc1x: "/img/webp/foco__coconut__water.webp",
          webpSrc2x: "/img/webp/foco__coconut__water__2x.webp",
          volumes: [330, 1000],
          prices: [120, 348],
          ingredients: "натуральная кокосовая вода 100%",
          quantity: 3,
          id: "1sw4p"
        },
      ],
    },
    {
      id: 'section__juice',
      title: "Соки",
      cards: [
        {
          name: "CОК АПЕЛЬСИНОВЫЙ СВЕЖЕВЫЖАТЫЙ",
          imgSrc1x: "/img/2sj1i.png",
          imgSrc2x: "/img/2x/2sj1i__2x.png",
          webpSrc1x: "/img/webp/2sj1i.webp",
          webpSrc2x: "/img/webp/2sj1i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "2sj1p"
        },
        {
          name: "СОК ВИШНЕВЫЙ СВЕЖЕВЫЖАТЫЙ",
          imgSrc1x: "/img/2sj2i.png",
          imgSrc2x: "/img/2x/2sj2i__2x.png",
          webpSrc1x: "/img/webp/2sj2i.webp",
          webpSrc2x: "/img/webp/2sj2i__2x.webp",
          volumes: [500, 1000, 1500],
          prices: [100, 150, 200],
          ingredients: "djdjdjdjdjdjdjdjdjdjdjd",
          quantity: 3,
          id: "2sj2p"
        },
        {
          name: "ITO NOEN СОК ЮДЗУ 100%я",
          imgSrc1x: "/img/2sj3i.png",
          imgSrc2x: "/img/2x/2sj3i__2x.png",
          webpSrc1x: "/img/webp/2sj3i.webp",
          webpSrc2x: "/img/webp/2sj3i__2x.webp",
          volumes: [100, 900],
          prices: [760, 5390],
          ingredients: "сок цитруса юдзу 100%",
          quantity: 3,
          id: "2sj3p"
        },
        {
          name: "СОК ХОЛОДНОГО ОТЖИМА CITRUS 3",
          imgSrc1x: "/img/2sj4i.png",
          imgSrc2x: "/img/2x/2sj4i__2x.png",
          webpSrc1x: "/img/webp/2sj4i.webp",
          webpSrc2x: "/img/webp/2sj4i__2x.webp",
          volumes: [330],
          prices: [420],
          ingredients: "грейпфрут свежий, мята свежая",
          quantity: 3,
          id: "2sj4p",
          productDescription: "Citrus – соки богаты витамином С, стимулируют обмен веществ и мобилизуют силы.",
          ratingValue:"4.8"
        },
      ],
    },
    {
      id: 'section__fruit__drink',
      title: "Морсы",
      cards: [
        {
          name: "МОРС ИЗ ЧЕРНОЙ СМОРОДИНЫ",
          imgSrc1x: "/img/3sf-d1j.png",
          imgSrc2x: "/img/2x/3sf-d1j__2x.png",
          webpSrc1x: "/img/webp/3sf-d1j.webp",
          webpSrc2x: "/img/webp/3sf-d1j__2x.webp",
          volumes: [750, 1500],
          prices: [340, 640],
          ingredients: "Черная смородина, сахар, вода",
          quantity: 3,
          id: "3sf-d1p"
        },
        {
          name: "МОРС ИЗ ОБЛЕПИХИ",
          imgSrc1x: "/img/3sf-d2j.png",
          imgSrc2x: "/img/2x/3sf-d2j__2x.png",
          webpSrc1x: "/img/webp/3sf-d2j.webp",
          webpSrc2x: "/img/webp/3sf-d2j__2x.webp",
          volumes: [750, 1500],
          prices: [340, 680],
          ingredients: "Облепиха, сахар, вода",
          quantity: 3,
          id: "3sf-d2p"
        },
        {
          name: "МОРС ИЗ БРУСНИКИ",
          imgSrc1x: "/img/3sf-d3j.png",
          imgSrc2x: "/img/2x/3sf-d3j__2x.png",
          webpSrc1x: "/img/webp/3sf-d3j.webp",
          webpSrc2x: "/img/webp/3sf-d3j__2x.webp",
          volumes: [750, 1500],
          prices: [460, 920],
          ingredients: "Брусника, сахар, вода",
          sale: 50,
          quantity: 3,
          id: "3sf-d3p"
        },
        {
          name: "МОРС ИЗ КЛЮКВЫ",
          imgSrc1x: "/img/3sf-d4j.png",
          imgSrc2x: "/img/2x/3sf-d4j__2x.png",
          webpSrc1x: "/img/webp/3sf-d4j.webp",
          webpSrc2x: "/img/webp/3sf-d4j__2x.webp",
          volumes: [750, 1500],
          prices: [340, 640],
          ingredients: "Клюква, сахар, вода",
          quantity: 3,
          id: "3sf-d4p"
        },
      ],
    },
    {
      id: 'section__smoothie',
      title: "Смузи",
      cards: [
        {
          name: "CLEAR BARN СМУЗИ HEY, МИНЬОН!",
          imgSrc1x: "/img/4ss1i.png",
          imgSrc2x: "/img/2x/4ss1i__2x.png",
          webpSrc1x: "/img/webp/4ss1i.webp",
          webpSrc2x: "/img/webp/4ss1i__2x.webp",
          volumes: [300],
          prices: [350],
          ingredients: "кокосовое молоко, апельсин, манго, авокадо, пюре манго, пюре маракуйя",
          quantity: 3,
          id: "4ss1p"
        },
        {
          name: "CLEAR BARN СМУЗИ COSMOS",
          imgSrc1x: "/img/4ss2i.png",
          imgSrc2x: "/img/2x/4ss2i__2x.png",
          webpSrc1x: "/img/webp/4ss2i.webp",
          webpSrc2x: "/img/webp/4ss2i__2x.webp",
          volumes: [300],
          prices: [380],
          ingredients: "груша, ананас, манго, вода, яблоко, миндаль, сок лайма",
          quantity: 3,
          id: "4ss2p"
        },
        {
          name: "CLEAR BARN СМУЗИ MR. FLANINGO ",
          imgSrc1x: "/img/4ss3i.png",
          imgSrc2x: "/img/2x/4ss3i__2x.png",
          webpSrc1x: "/img/webp/4ss3i.webp",
          webpSrc2x: "/img/webp/4ss3i__2x.webp",
          volumes: [300],
          prices: [350],
          ingredients: "кокосовое молоко, груша, малина, вода, миндаль, авокадо, пюре лесные ягоды",
          quantity: 3,
          id: "4ss3p"
        },
        {
          name: "CLEAR BARN СМУЗИ SUPER GIRL",
          imgSrc1x: "/img/4ss4i.png",
          imgSrc2x: "/img/2x/4ss4i__2x.png",
          webpSrc1x: "/img/webp/4ss4i.webp",
          webpSrc2x: "/img/webp/4ss4i__2x.webp",
          volumes: [300],
          prices: [380],
          ingredients: "ананас, кокосовое молоко, апельсин, банан, сок лайма, коэнзим Q10",
          sale: 50,
          quantity: 3,
          id: "4ss4p"
        }
      ],
    },
    {
      id: 'section__sport__drink',
      title: "Спортивные напикти",
      cards: [
        {
          name: "ИЗОТОНИК POWERADE",
          imgSrc1x: "/img/5ss-d1i.png",
          imgSrc2x: "/img/2x/5ss-d1i__2x.png",
          webpSrc1x: "/img/webp/5ss-d1i.webp",
          webpSrc2x: "/img/webp/5ss-d1i__2x.webp",
          volumes: [500, 900],
          prices: [90, 183],
          ingredients: "вода очищенная; подсластитель; калия цитрат; фруктоза; декстроза; магния хлорид; калия фосфат; ароматизатор натуральный; регулятор кислотности лимонная кислота; хлорид кальция",
          quantity: 3,
          id: "5ss-d1p"
        },
        {
          name: "ГИПОТоНИЧЕСКИЙ НАПИТОК Unisport",
          imgSrc1x: "/img/5ss-d2i.png",
          imgSrc2x: "/img/2x/5ss-d2i__2x.png",
          webpSrc1x: "/img/webp/5ss-d2i.webp",
          webpSrc2x: "/img/webp/5ss-d2i__2x.webp",
          volumes: [1000],
          prices: [2948],
          ingredients: "сахар, регулятор кислотности лимонная кислота, вода, ароматизатор, хлорид натрия, глюконат магния, таурин, L-карнитин, L-аланин, подсластитель ацесульфам К, монокалийфосфат, подсластитель сукралоза, краситель Е 122",
          sale: 50,
          quantity: 3,
          id: "5ss-d2p"
        },
      ],
    },
  ];